export const TRY_AUTO_LOGIN = "TRY_AUTO_LOGIN";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const INITIATE_LOGOUT = "INITIATE_LOGOUT";
export const LOGOUT = "LOGOUT";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const FETCH_CURRENT_USER = "FETCH_CURRENT_USER";

export const FETCH_ARTICLES = "ARTICLES";
export const FETCH_ARTICLES_START = "FETCH_ARTICLES_START";
export const FETCH_ARTICLES_SUCCESS = "FETCH_ARTICLES_SUCCESS";
export const FETCH_ARTICLES_FAIL = "FETCH_ARTICLES_FAIL";
export const GET_ARTICLE = "GET_ARTICLE";

export const SET_ARTICLE_PAGINATION_PARAMS = "SET_ARTICLE_PAGINATION_PARAMS";

export const FETCH_GLOBAL_FEEDS = "FETCH_GLOBAL_FEEDS";
export const FETCH_GLOBAL_FEEDS_START = "FETCH_GLOBAL_FEEDS_START";
export const FETCH_GLOBAL_FEEDS_SUCCESS = "FETCH_GLOBAL_FEEDS_SUCCESS";
export const FETCH_GLOBAL_FEEDS_FAIL = "FETCH_GLOBAL_FEEDS_FAIL";
export const SET_GLOBAL_FEEDS_PAGINATION_PARAMS =
  "SET_GLOBAL_FEEDS_PAGINATION_PARAMS";

export const ADD_ARTICLE = "ADD_ARTICLE";
export const ADD_ARTICLE_START = "ADD_ARTICLE_START";
export const ADD_ARTICLE_SUCCESS = "ADD_ARTICLE_SUCCESS";
export const ADD_ARTICLE_FAIL = "ADD_ARTICLE_FAIL";
export const FETCH_ARTICLE = "FETCH_ARTICLE";
export const FETCH_ARTICLE_START = "FETCH_ARTICLE_START";
export const FETCH_ARTICLE_SUCCESS = "FETCH_ARTICLE_SUCCESS";
export const FETCH_ARTICLE_FAIL = "FETCH_ARTICLE_FAIL";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS";

export const COMMENT_ADD = "COMMENT_ADD";
export const COMMENT_ADD_START = "COMMENT_ADD_START";
export const COMMENT_ADD_SUCCESS = "COMMENT_ADD_SUCCESS";
export const COMMENT_ADD_FAIL = "COMMENT_ADD_FAIL";
export const COMMENT_DELETE = "COMMENT_DELETE";
export const COMMENT_DELETE_SUCCESS = "COMMENT_DELETE_SUCCESS";
export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
